# Generated by Django 3.1.7 on 2021-03-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210311_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='landregister',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
