# Generated by Django 3.1.7 on 2021-03-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210311_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Store',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='LandRegister',
        ),
    ]
