# Generated by Django 3.1.7 on 2021-03-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210311_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('payment pending', 'payment pending'), ('searching', 'searching'), ('printed', 'printed'), ('stamped', 'stamped'), ('delivered', 'delivered')], default='payment pending', max_length=25),
        ),
    ]
