# Generated by Django 3.1.7 on 2021-03-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210312_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['ticket']},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='number',
            new_name='ticket',
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='search',
            field=models.CharField(choices=[('S', 'search'), ('LR', 'land register'), ('I', 'instrument')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='block',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='parcel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
