# Generated by Django 3.1.7 on 2021-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210312_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='search',
            field=models.CharField(choices=[('search', 'search'), ('land register', 'land register'), ('instrument', 'instrument')], max_length=20, null=True),
        ),
    ]
